[package]
edition = "2024"
name = "project-name"
version = "0.1.0"

[dependencies]
dma-api = {version = "0.7"}
log = "0.4"
mbarrier = "0.1"

[dev-dependencies]
bare-test = "0.7"

[build-dependencies]
bare-test-macros = "0.2"

[[test]]
harness = false
name = "test"
